### PR TITLE
Ci updated

### PR DESCRIPTION
**Pull request by sagudev**
Fix for #19 
Fix all clippy warnings.
Fix formatting.
Format and lint is only in GitHub Workflow now.
For linting https://github.com/marketplace/actions/rust-clippy-check is used.

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
Heeey, this is pretty awesome! :smile:

**Comment by ricochet1k** [comment]
Yikes, that's a scary config file. Please don't just verbatim copy from another project, they have different requirements than we do. The error message from Appveyor on the existing repo is relating to libz-sys, which has a much smaller Appveyor.yml file, but even it shouldn't be copied verbatim, because *we don't need to build those projects* we only need to depend on them. In particular, you've removed the use of clippy and the cache settings.

Can we go back to what we had and only figure out what minimal changed we need to make CI work again?

**Comment by sagudev** [comment]
Its still work in progress.

**Comment by ricochet1k** [comment]
> Its still work in progress.

Yes, sorry. Thank you for trying to fix it! I'm just trying to provide guidance.

**Comment by sagudev** [comment]
@ricochet1k I think clippy parts aren't really for AppVeyor. Maybe use formatting and linting in prepush hook (https://github.com/cloudflare/wrangler/pull/258/commits/48a22f7198d59a547690e8a4e01cc093b0b618f8) or maybe putting this from AppVeyor to Github workflows.

**Comment by sagudev** [comment]
I think it's finished.

**Pull request merged**
